Config = {}

Config.Accounts = {
	bank = "banque",
	black_money = "argent sale",
	money = "espèces"
}

Config.StartingAccountMoney = {money = 0, bank = 0}

Config.EnableSocietyPayouts = false -- pay from the society account that the player is employed at? Requirement: society
Config.EnableHud            = true -- enable the default hud? Display current job and accounts (black, bank & cash)
Config.MaxWeight            = 150   -- the max inventory weight without backpack
Config.PaycheckInterval     = 10 * 60000 -- how often to recieve pay checks in milliseconds
Config.EnableDebug          = false
Config.Licenses             = {
	["weapon"] = {name = "Permis de port d'arme", type = "weapon"},
	["car"] = {name = "Permis de conduire", type = "car"}
}


Config.Items = {
    { label = "Eau", name = "water", price = 50, categorie = "food", shop = "shop", type = "item", image = "assets/water.png" },
    { label = "Pain", name = "bread", price = 50, categorie = "food", shop = "shop", type = "item", image = "assets/bread.png" },
    { label = "Téléphone", name = "phone", price = 500, categorie = "divers", shop = "shop", type = "item", image = "assets/phone.png" },
    { label = "Radio", name = "radio", price = 500, categorie = "divers", shop = "shop", type = "item", image = "assets/radio.png" },



    --Ammunation--
    { label = "Batte de Baseball", name = "WEAPON_BAT", price = 7000, categorie = "armes", shop = "ammunation", type = "weapon", image = "assets/weapon_bat.png" },
    { label = "Poing américain", name = "WEAPON_KNUCKLE", price = 5000, categorie = "armes", shop = "ammunation", type = "weapon", image = "assets/weapon_knuckle.png" },
    { label = "Couteau", name = "weapon_knife", price = 5000, categorie = "armes", shop = "ammunation", type = "weapon", image = "assets/weapon_knife.png" },
    { label = "Pétoire", name = "weapon_snspistol", price = 180000, categorie = "armes", shop = "ammunation", type = "weapon", image = "assets/weapon_snspistol.png" },

    { label = "12gauge", name = "12mm", price = 10, categorie = "munitions", shop = "ammunation", type = "item", image = "assets/ammo_shotgun.png" },
    { label = "5.56mm", name = "556mm", price = 10, categorie = "munitions", shop = "ammunation", type = "item", image = "assets/ammo_5_56.png" },
    { label = "Kal.68", name = "68kal", price = 10, categorie = "munitions", shop = "ammunation", type = "item", image = "assets/ammo_musket.png" },
    { label = "7.62mm", name = "762mm", price = 10, categorie = "munitions", shop = "ammunation", type = "item", image = "assets/ammo_7.62.png" },
    { label = "9mm", name = "9mm", price = 10, categorie = "munitions", shop = "ammunation", type = "item", image = "assets/ammo_9.png" },

    --Ikea--
    { label = "Chaise 3 places", name = "prop_fib_3b_bench", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Ancien canapé 1 place", name = "prop_ld_farm_chair01", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Ancien canapé 3 places", name = "prop_ld_farm_couch01", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Vieux canapé rayé", name = "prop_ld_farm_couch02", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Ancien canapé jaune 1 place", name = "v_res_d_armchair", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé d'angle", name = "v_res_fh_sofa", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé d'angle 2", name = "v_res_mp_sofa", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé ancien", name = "v_res_j_sofa", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé ancien de luxe", name = "v_res_m_h_sofa_sml", price = 10000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé 1", name = "v_res_d_sofa", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé 2", name = "v_res_mp_stripchair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé 3", name = "v_res_r_sofa", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé 4", name = "v_res_tre_sofa", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé 5", name = "v_res_tre_sofa_mess_a", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé 6", name = "v_res_tre_sofa_mess_b", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé 7", name = "v_res_tre_sofa_mess_c", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé 8", name = "v_res_tt_sofa", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé 9", name = "prop_rub_couch02", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Vieux canapé", name = "v_res_tre_sofa_mess_b", price = 40000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Vieux canapé usé", name = "v_res_tre_sofa_mess_c", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé en paille noir", name = "p_yacht_sofa_01_s", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Banc en bois", name = "prop_table_08_chr", price = 40000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Banc d'extérieur métalique", name = "v_res_fh_benchshort", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Canapé en cuir noir", name = "v_corp_cd_recseat", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise haute", name = "v_res_d_highchair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise", name = "v_res_fa_chair01", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise", name = "v_res_fa_chair02", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise haute", name = "v_res_fh_barcchair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de salle à manger 1", name = "v_res_fh_dineeamesa", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de salle à manger 2", name = "v_res_fh_dineeamesb", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise Plastique", name = "prop_table_03_chr", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise Plastique 2", name = "prop_table_03b_chr", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de salle à manger 3", name = "v_res_fh_dineeamesc", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de salle à manger 4", name = "v_res_j_dinechair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise", name = "v_res_fh_easychair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Tabouret", name = "v_res_fh_kitnstool", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise haute", name = "v_res_fh_singleseat", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Tabouret", name = "v_res_j_stool", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de bureau", name = "v_res_mbchair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Fauteuil 1", name = "v_res_jarmchair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Fauteuil 2", name = "v_res_m_armchair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Fauteuil 3", name = "p_armchair_01_s", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Fauteuil 4", name = "prop_armchair_01", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Dine Chair", name = "v_res_m_dinechair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaire d'étude", name = "v_res_study_chair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise", name = "v_res_trev_framechair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise", name = "v_res_tre_chair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de bureau", name = "v_res_tre_officechair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Tabouret", name = "v_res_tre_stool", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Tabouret en cuir", name = "v_res_tre_stool_leather", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Tabouret en cuir détérioré", name = "v_res_tre_stool_scuz", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de bureau", name = "v_med_p_deskchair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Petit canapé", name = "v_med_p_easychair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise Whicker", name = "v_med_whickerchair1", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise en bois 1", name = "prop_direct_chair_01", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise en bois 2", name = "prop_direct_chair_02", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Siège transat 1", name = "prop_yacht_lounger", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Siège transat 2", name = "prop_yacht_seat_01", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Siège transat 3", name = "prop_yacht_seat_02", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Siège transat 4", name = "prop_yacht_seat_03", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise blanche", name = "v_ret_chair_white", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise", name = "v_ret_chair", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Tabouret petit", name = "v_ret_ta_stool", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de bureau", name = "prop_cs_office_chair", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise 01", name = "v_ret_gc_chair01", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise 02", name = "v_ret_gc_chair02", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Siège de bureau 1", name = "prop_off_chair_01", price = 40000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Siège de bureau 2", name = "prop_off_chair_03", price = 40000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Siège de bureau 3", name = "prop_off_chair_04", price = 40000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Fauteuil en cuir", name = "prop_sol_chair", price = 40000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Fauteuil en paille noir", name = "p_yacht_chair_01_s", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de réalisateur", name = "prop_direct_chair_01", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise en bois rare", name = "p_dinechair_01_s", price = 10000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Vielle chaise", name = "prop_chair_03", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise bleu", name = "gr_prop_gr_chair02_ped", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise en métal 1", name = "prop_chair_01a", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise en métal 2", name = "prop_chair_01b", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise en plastique blanc", name = "prop_chair_08", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise tressé rouge", name = "prop_chateau_chair_01", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de camping 1", name = "prop_skid_chair_02", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de camping 2", name = "prop_skid_chair_01", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de camping 3", name = "prop_skid_chair_03", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de bureau", name = "v_corp_offchair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise confortable", name = "v_ilev_p_easychair", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Fauteuil de bureau noir", name = "sm_prop_offchair_smug_01", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Fauteuil de bureau blanc", name = "sm_prop_offchair_smug_02", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise gaming rouge", name = "gr_prop_highendchair_gr_01a", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Fauteuil vert", name = "v_med_fabricchair1", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de torture", name = "prop_torture_ch_01", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise de cuisine", name = "v_ilev_fh_kitchenstool", price = 40000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 1", name = "v_res_d_bed", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 2", name = "v_res_lestersbed", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 3", name = "v_res_mbbed", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 4", name = "v_res_mdbed", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 5", name = "v_res_msonbed", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 6", name = "v_res_tre_bed1", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 7", name = "v_res_tre_bed2", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 8", name = "v_res_tt_bed", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 9", name = "prop_t_sofa_02", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 10", name = "v_res_msonbed_s", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 11", name = "p_lestersbed_s", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 12", name = "p_mbbed_s", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Lit 13", name = "p_v_res_tt_bed_s", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Poussette 1", name = "dolu_prop_stroller1", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Poussette 2", name = "dolu_prop_stroller2", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Pouf cube", name = "v_res_fh_pouf", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Pouf rose", name = "v_corp_facebeanbag", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Pouf violet", name = "v_corp_facebeanbagc", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Pouf bleu", name = "v_corp_facebeanbagd", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Carte de la ville", name = "v_16_high_pln_m_map", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Bar de Traction", name = "prop_a_base_bars_01", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Sac de Boxe", name = "prop_punch_bag_l", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Tapis de yoga 1", name = "prop_yoga_mat_01", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Tapis de yoga 2", name = "prop_yoga_mat_02", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Tapis de yoga 3", name = "prop_yoga_mat_03", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Table Bras de Fer", name = "prop_arm_wrestle_01", price = 80000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Tableau", name = "prop_scrim_02", price = 50000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Tableau de craie", name = "v_res_mchalkbrd", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Muscu 1", name = "prop_barbell_01", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Muscu 2", name = "prop_barbell_02", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Muscu 3", name = "prop_barbell_100kg", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Muscu 4", name = "prop_barbell_10kg", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Muscu 5", name = "prop_barbell_20kg", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Muscu 6", name = "prop_barbell_40kg", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Muscu 7", name = "prop_barbell_60kg", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Muscu 8", name = "prop_barbell_80kg", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Muscu 9", name = "prop_barbell_junk", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise en plastique cassé", name = "v_ret_gc_chair03", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Muscu 10", name = "prop_weight_squat", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Muscu 11", name = "prop_weight_squat_02", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise bleu cassé", name = "prop_cs_office_chair_01", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise métallique", name = "prop_cs_office_chair_02", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Chaise verte cassé", name = "prop_cs_office_chair_03", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Cintre mural 1", name = "v_res_msonbed_s", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Cintre mural 2", name = "prop_fleeca_atm", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" },
    { label = "Muscu 12", name = "v_res_mbbed_s", price = 20000, categorie = "props", shop = "ikea", type = "props", image = "assets/shipping_box.png" }
    
}