-- Ajout des armes et de leurs labels
AddTextEntry("WEAPON_KATANA", "Katana")
AddTextEntry("WEAPON_KATANA2", "Katana2")
AddTextEntry("WEAPON_SPIKEDCLUB", "Spikbatt")
AddTextEntry("WEAPON_KNIFE2", "Knife2")

-- Pistolets
AddTextEntry("WEAPON_PISTOLBLACK", "Pistol Black")
AddTextEntry("WEAPON_PISTOLCALIBRE50", "Pokemon Orange")
AddTextEntry("WEAPON_PISTOLPOKA", "Pokemon Rouge")
AddTextEntry("WEAPON_PISTOLWHITE", "Pistol White")
AddTextEntry("WEAPON_KERTUS", "Kertus")
AddTextEntry("WEAPON_SCORPION", "Scorpion")

-- Snipers
AddTextEntry("WEAPON_BLACKSNIPER", "Blacksniper")
AddTextEntry("WEAPON_RGXOPERATOR", "RGX Operator")
AddTextEntry("WEAPON_MARKSMANRIFLE2", "Marksman Rifle 2")

-- AK et autres armes
AddTextEntry("WEAPON_AKMK01", "AkBleu")
AddTextEntry("WEAPON_ANIMEM4", "Animem4")
AddTextEntry("WEAPON_CARBINERIFLE2", "Glishpop")
AddTextEntry("WEAPON_CARBINERIFLE3", "RedWhite")
AddTextEntry("WEAPON_CARBINERIFLE4", "BleuAR")
AddTextEntry("WEAPON_CARBINERIFLE5", "GoldAR")
AddTextEntry("WEAPON_CARBINERIFLE6", "RedAR15")
AddTextEntry("WEAPON_CARBINERIFLE7", "IceAR")
AddTextEntry("WEAPON_JOSM4A4CH", "ARnoel")
AddTextEntry("WEAPON_MENACE", "Menace")
AddTextEntry("WEAPON_SPECIALCARBINE2_MK2", "VandalAraxys")
AddTextEntry("WEAPON_SPECIALCARBINE3", "Dragon")
AddTextEntry("WEAPON_VANDALEX", "VandalRever")

AddTextEntry('WEAPON_TAZ', 'Tazer LSPD')
AddTextEntry('WEAPON_GLOCK20', 'Glock 20')
AddTextEntry('WT_FAKEGNADE_SMK', 'Grenade Fumigène M18')
AddTextEntry('WT_PELLE', 'Pelle')
AddTextEntry('WT_CANETTE', 'Canette')
AddTextEntry('WT_BRICK', 'Brique')
AddTextEntry('WT_TOMATO', 'Tomate')
AddTextEntry('WT_BOUTEILLE', 'Bouteille Cassé Jetable')
AddTextEntry('WT_SLEDGEHAMMER', 'Masse')
AddTextEntry('WT_PICKAXE', 'Pioche')
AddTextEntry('WT_PIST_FAKECBT', 'Pistolet de combat non létale')
AddTextEntry('WT_FAKESMG', 'MP5 non létale')
AddTextEntry('WT_BEAMBAG', 'Bean bag')
AddTextEntry('WT_CHAINSAW', 'Tronçonneuse')
AddTextEntry('WT_NAILGUN', 'Pistolet à clou')
AddTextEntry('WT_FAKEAK', 'Ak47 non létale')
AddTextEntry('WT_FAKEUZI', 'UZI non létale')
AddTextEntry('WT_FAKEAKU', 'AKu non létale')
AddTextEntry('WT_FAKESHOTGUN', 'Fusil à pompe non létale')
AddTextEntry('WT_FAKESKORPION', 'Skorpion non létale')
AddTextEntry('WT_KATANA2', 'Katana')
AddTextEntry('WT_KATANA3', 'Katana')
AddTextEntry('WT_KATANA4', 'Katana')
AddTextEntry('WT_KATANA5', 'Katana')
AddTextEntry('WT_KATANA6', 'Katana')
AddTextEntry('WT_FAKEM4', 'M4A1 non létale')
AddTextEntry('WEAPON_TOZ', 'Toz')
AddTextEntry('WT_PAINTBALL', 'Paintball')
AddTextEntry('WT_FLAMETHROWER', 'Lance Flamme')
AddTextEntry('WT_MOLETTE', 'MOLETTE')
AddTextEntry('WT_LIBERTY_STATUE', 'Statue de la Liberté')
AddTextEntry('WT_PHONE', 'Téléphone')
AddTextEntry('WT_GUITAR', 'Guitare')
AddTextEntry('WT_PLASMAP', 'Plasma Pistol')
AddTextEntry('WT_WATERPISTOL', 'Pistolet a eau')
AddTextEntry('WT_RADARPISTOL', 'Pistolet Radar')
AddTextEntry('WT_UVLIGHT', 'Lampe UV')
AddTextEntry('WEAPON_WATERING', 'Arrosoire')
AddTextEntry('WT_JREVOLVER', 'Judge Revolver')
AddTextEntry('WEAPON_GLOCK', 'Glock')
AddTextEntry('WEAPON_HK417', 'HK417')
AddTextEntry('WEAPON_M9', 'M9')
AddTextEntry('WEAPON_OLD_SHOTGUN', 'Fusil a pompe (usé)')
AddTextEntry('WEAPON_UZI', 'Uzi')
AddTextEntry('WEAPON_AK', 'AK')
AddTextEntry('WEAPON_SNUB', '.357 Snub')
AddTextEntry('WEAPON_HUNT', 'Sauer 101 Hunting Rifle')
AddTextEntry('WEAPON_STUNGUN_02', 'Tazer Vert')
AddTextEntry('WEAPON_MICHAELMYERS', 'Couteaux Ensanglanté')
AddTextEntry('WEAPON_LEATHERFACE_HATCHET', 'Tronsoneuse')
AddTextEntry('WEAPON_LEATHERFACE_HAMMER', 'Marteaux V2')
AddTextEntry('WEAPON_JASONVOORHEES', 'Machette V2')
AddTextEntry('WEAPON_CHUCKY', 'Tourne Vis Chucky')
AddTextEntry('WEAPON_DARTHVADER', 'Sabre Laser')
AddTextEntry('WEAPON_SCYTHE', 'Faux')
AddTextEntry('WEAPON_SECURITYCASE', 'Mallette Sécurisée')
AddTextEntry('WEAPON_TOOLBOX', 'Caisse à outils')
AddTextEntry('WEAPON_BUMBLEBEE', 'Bumblebee')
AddTextEntry("WEAPON_SCARH", "SCAR-H")
AddTextEntry("WT_NEWSPAPER", "Journal")
