VehicleShops = {
    ["cardealer"] = {
        type = "car",
        label = "Luxury Autoshop",
        zones = {
            ["boss"] = vector3(239.98, -272.35, 53.98),
            ["reseller"] = vector3(249.05, -286.17, 53.98),
            ["katalog"] = vector3(254.83, -283.94, 54.01),
            ["kataenter"] = vector(250.32, -284.34, 52.98),
            ["spawn"] = vector3(293.17, -278.15, 53.98)
        }
    },
    ["planedealer"] = {
        type = "plane",
        label = "Luxury Planeshop",
        zones = {
            ["boss"] = vector3(-1307.24, -3389.62, 12.94),
            ["reseller"] = vector3(-1242.23, -3393.45, 12.94),
            ["katalog"] = vector3(-1267.9, -3392.83, 12.94),
            ["kataenter"] = vector(-1244.67, -3381.7, 12.94),
            ["spawn"] = vector3(-1244.72, -3328.86, 12.95)
        }
    }
} 

function CheckIsVehicleDealer(job)
    if VehicleShops[job] then
        return true
    else
        return false
    end
end

Categories = {
    { label = "Compacts", name = "compacts", type = "car" },
    { label = "Coupés", name = "coupes", type = "car" },
    { label = "Motos", name = "motorcycles", type = "car" },
    { label = "Muscle", name = "muscle", type = "car" },
    { label = "Off Road", name = "offroad", type = "car" },
    { label = "Sedans", name = "sedans", type = "car" },
    { label = "Sports", name = "sports", type = "car" },
    { label = "Sports Classics", name = "sportsclassics", type = "car" },
    { label = "Super", name = "super", type = "car" },
    { label = "SUVs", name = "suvs", type = "car" },
    { label = "Vans", name = "vans", type = "car" },
    { label = "Avions", name = "planes", type = "plane" },
}

Vehicles = {
    { category = "super", categoryLabel = "Super", price = 4000000, model = "adder", name = "Adder", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 35000, model = "AKUMA", name = "Akuma", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 100000, model = "alpha", name = "Alpha", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 40000, model = "asea", name = "Asea", type = "car" },
    { category = "super", categoryLabel = "Super", price = 2000000, model = "autarch", name = "Autarch", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 50000, model = "avarus", name = "Avarus", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 40000, model = "bagger", name = "Bagger", type = "car" },
    { category = "suvs", categoryLabel = "SUVs", price = 150000, model = "baller2", name = "Baller", type = "car" },
    { category = "suvs", categoryLabel = "SUVs", price = 250000, model = "baller3", name = "Baller Sport", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 100000, model = "banshee", name = "Banshee", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 250000, model = "banshee2", name = "Banshee 900R", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 50000, model = "bati", name = "Bati 801", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 60000, model = "bati2", name = "Bati 801RR", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 200000, model = "bestiagts", name = "Bestia GTS", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 40000, model = "bf400", name = "BF400", type = "car" },
    { category = "offroad", categoryLabel = "Off Road", price = 20000, model = "bfinjection", name = "Bf Injection", type = "car" },
    { category = "offroad", categoryLabel = "Off Road", price = 80000, model = "bifta", name = "Bifta", type = "car" },
    { category = "vans", categoryLabel = "Vans", price = 150000, model = "bison", name = "Bison", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 35500, model = "blade", name = "Blade", type = "car" },
    { category = "offroad", categoryLabel = "Off Road", price = 25000, model = "blazer", name = "Blazer", type = "car" },
    { category = "offroad", categoryLabel = "Off Road", price = 62000, model = "blazer4", name = "Blazer Sport", type = "car" },
    { category = "compacts", categoryLabel = "Compacts", price = 30000, model = "blista", name = "Blista", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 1000, model = "bmx", name = "BMX (velo)", type = "car" },
    { category = "compacts", categoryLabel = "Compacts", price = 40000, model = "brioso", name = "Brioso R/A", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 250000, model = "btype", name = "Btype", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 350000, model = "btype3", name = "Btype Luxe", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 60000, model = "buccaneer", name = "Buccaneer", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 75000, model = "buccaneer2", name = "Buccaneer Rider", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 75000, model = "buffalo", name = "Buffalo", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 85000, model = "buffalo2", name = "Buffalo S", type = "car" },
    { category = "super", categoryLabel = "Super", price = 200000, model = "bullet", name = "Bullet", type = "car" },
    { category = "vans", categoryLabel = "Vans", price = 70000, model = "burrito3", name = "Burrito", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 80000, model = "carbonrs", name = "Carbon RS", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 380000, model = "casco", name = "Casco", type = "car" },
    { category = "super", categoryLabel = "Super", price = 2500000, model = "cheetah", name = "Cheetah", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 80000, model = "chimera", name = "Chimera", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 45000, model = "chino", name = "Chino", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 60000, model = "chino2", name = "Chino Luxe", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 70000, model = "cliffhanger", name = "Cliffhanger", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 250000, model = "cogcabrio", name = "Cognoscenti Cabrio", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 300000, model = "cognoscenti", name = "Cognoscenti", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 500000, model = "comet2", name = "Comet", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 750000, model = "comet5", name = "Comet Electric", type = "car" },
    { category = "suvs", categoryLabel = "SUVs", price = 250000, model = "contender", name = "Contender", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 400000, model = "coquette", name = "Coquette", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 450000, model = "coquette2", name = "Coquette Classic", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 450000, model = "coquette3", name = "Coquette BlackFin", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 2000, model = "cruiser", name = "Cruiser (velo)", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 70000, model = "daemon", name = "Daemon", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 80000, model = "daemon2", name = "Daemon High", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 200000, model = "dominator", name = "Dominator", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 75000, model = "double", name = "Double T", type = "car" },
    { category = "suvs", categoryLabel = "SUVs", price = 150000, model = "dubsta", name = "Dubsta", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 210000, model = "dukes", name = "Dukes", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 400000, model = "elegy2", name = "Elegy", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 80000, model = "emperor", name = "Emperor", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 55000, model = "enduro", name = "Enduro", type = "car" },
    { category = "super", categoryLabel = "Super", price = 1500000, model = "entityxf", name = "Entity XF", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 100000, model = "exemplar", name = "Exemplar", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 120000, model = "f620", name = "F620", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 180000, model = "faction", name = "Faction", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 260000, model = "faction2", name = "Faction Rider", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 5000, model = "faggio", name = "Faggio", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 10000, model = "faggio2", name = "Vespa", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 200000, model = "felon", name = "Felon", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 250000, model = "felon2", name = "Felon GT", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 500000, model = "feltzer2", name = "Feltzer", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 654130, model = "feltzer3", name = "Stirling GT", type = "car" },
    { category = "super", categoryLabel = "Super", price = 1125300, model = "fmj", name = "FMJ", type = "car" },
    { category = "suvs", categoryLabel = "SUVs", price = 170000, model = "fq2", name = "Fhantom", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 120000, model = "fugitive", name = "Fugitive", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 300000, model = "furoregt", name = "Furore GT", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 175000, model = "fusilade", name = "Fusilade", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 60000, model = "gargoyle", name = "Gargoyle", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 200000, model = "gauntlet", name = "Gauntlet", type = "car" },
    { category = "suvs", categoryLabel = "SUVs", price = 250000, model = "granger", name = "Granger", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 500000, model = "gt500", name = "GT 500", type = "car" },
    { category = "offroad", categoryLabel = "Off Road", price = 350000, model = "guardian", name = "Guardian", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 100000, model = "hakuchou", name = "Hakuchou", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 75000, model = "hexer", name = "Hexer", type = "car" },
    { category = "suvs", categoryLabel = "SUVs", price = 250000, model = "huntley", name = "Huntley", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 150000, model = "hustler", name = "Hustler", type = "car" },
    { category = "super", categoryLabel = "Super", price = 400000, model = "infernus", name = "Infernus", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 80000, model = "innovation", name = "Innovation", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 80000, model = "intruder", name = "Intruder", type = "car" },
    { category = "compacts", categoryLabel = "Compacts", price = 50000, model = "issi2", name = "Issi", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 300000, model = "jackal", name = "Jackal", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 600000, model = "jester", name = "Jester", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 750000, model = "jester2", name = "Jester(Racecar)", type = "car" },
    { category = "offroad", categoryLabel = "Off Road", price = 250000, model = "kamacho", name = "Kamacho", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 150000, model = "khamelion", name = "Khamelion", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 500000, model = "kuruma", name = "Kuruma", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 350000, model = "lynx", name = "Lynx", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 300000, model = "mamba", name = "Mamba", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 70000, model = "manchez", name = "Manchez", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 200000, model = "massacro", name = "Massacro", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 250000, model = "massacro2", name = "Massacro(Racecar)", type = "car" },
    { category = "suvs", categoryLabel = "SUVs", price = 150000, model = "mesa", name = "Mesa", type = "car" },
    { category = "vans", categoryLabel = "Vans", price = 60000, model = "minivan", name = "Minivan", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 250000, model = "monroe", name = "Monroe", type = "car" },
    { category = "vans", categoryLabel = "Vans", price = 150000, model = "moonbeam", name = "Moonbeam", type = "car" },
    { category = "vans", categoryLabel = "Vans", price = 25000, model = "moonbeam2", name = "Moonbeam Rider", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 40000, model = "nemesis", name = "Nemesis", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 1250000, model = "neon", name = "Neon", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 100000, model = "nightshade", name = "Nightshade", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 180000, model = "ninef", name = "9F", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 220000, model = "ninef2", name = "9F Cabrio", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 250000, model = "oracle2", name = "Oracle XS", type = "car" },
    { category = "super", categoryLabel = "Super", price = 2000000, model = "osiris", name = "Osiris", type = "car" },
    { category = "compacts", categoryLabel = "Compacts", price = 30000, model = "panto", name = "Panto", type = "car" },
    { category = "vans", categoryLabel = "Vans", price = 100000, model = "paradise", name = "Paradise", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 400000, model = "pariah", name = "Pariah", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 42000, model = "pcj", name = "PCJ-600", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 75000, model = "penumbra", name = "Penumbra", type = "car" },
    { category = "super", categoryLabel = "Super", price = 500000, model = "pfister811", name = "Pfister", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 120000, model = "phoenix", name = "Phoenix", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 90000, model = "picador", name = "Picador", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 30000, model = "pigalle", name = "Pigalle", type = "car" },
    { category = "compacts", categoryLabel = "Compacts", price = 60000, model = "prairie", name = "Prairie", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 45000, model = "premier", name = "Premier", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 100000, model = "primo2", name = "Primo Custom", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 600000, model = "raiden", name = "raiden", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 60000, model = "rapidgt", name = "Rapid GT", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 80000, model = "rapidgt2", name = "Rapid GT Convertible", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 250000, model = "rapidgt3", name = "Rapid GT3", type = "car" },
    { category = "super", categoryLabel = "Super", price = 1000000, model = "reaper", name = "Reaper", type = "car" },
    { category = "offroad", categoryLabel = "Off Road", price = 100000, model = "rebel2", name = "Rebel", type = "car" },
    { category = "suvs", categoryLabel = "SUVs", price = 200000, model = "rocoto", name = "Rocoto", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 40000, model = "ruffian", name = "Ruffian", type = "car" },
    { category = "vans", categoryLabel = "Vans", price = 300000, model = "rumpo3", name = "Rumpo Trail", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 250000, model = "sabregt", name = "Sabre Turbo", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 200000, model = "sabregt2", name = "Sabre GT", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 60000, model = "sanchez", name = "Sanchez", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 70000, model = "sanchez2", name = "Sanchez Sport", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 40000, model = "sanctus", name = "Sanctus", type = "car" },
    { category = "offroad", categoryLabel = "Off Road", price = 300000, model = "sandking", name = "Sandking", type = "car" },
    { category = "super", categoryLabel = "Super", price = 1000000, model = "sc1", name = "SC 1", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 350000, model = "schafter2", name = "Schafter", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 400000, model = "schafter3", name = "Schafter V12", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 2000, model = "scorcher", name = "Scorcher (velo)", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 400000, model = "sentinel", name = "Sentinel", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 450000, model = "sentinel2", name = "Sentinel XS", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 150000, model = "sentinel3", name = "Sentinel Classic", type = "car" },
    { category = "super", categoryLabel = "Super", price = 1000000, model = "sheava", name = "ETR1", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 100000, model = "slamvan3", name = "Slam Van", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 300000, model = "stinger", name = "Stinger", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 450000, model = "stingergt", name = "Stinger GT", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 200000, model = "stretch", name = "Stretch", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 200000, model = "sultan", name = "Sultan", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 250000, model = "sultan2", name = "Sultan Classic", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 300000, model = "sultanrs", name = "Sultan RS", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 300000, model = "superd", name = "Super Diamond", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 200000, model = "surano", name = "Surano", type = "car" },
    { category = "super", categoryLabel = "Super", price = 2000000, model = "t20", name = "T20", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 100000, model = "tailgater", name = "Tailgater", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 75000, model = "thrust", name = "Thrust", type = "car" },
    { category = "sports", categoryLabel = "Sports", price = 350000, model = "tropos", name = "Tropos", type = "car" },
    { category = "super", categoryLabel = "Super", price = 900000, model = "turismor", name = "Turismo R", type = "car" },
    { category = "super", categoryLabel = "Super", price = 1000000, model = "vacca", name = "Vacca", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 100000, model = "vader", name = "Vader", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 125000, model = "vigero", name = "Vigero", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 400000, model = "virgo", name = "Virgo", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 300000, model = "viseris", name = "Viseris", type = "car" },
    { category = "super", categoryLabel = "Super", price = 1850000, model = "visione", name = "Visione", type = "car" },
    { category = "super", categoryLabel = "Super", price = 450000, model = "voltic", name = "Voltic", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 95000, model = "voodoo", name = "Voodoo", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 60000, model = "vortex", name = "Vortex", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 45000, model = "warrener", name = "Warrener", type = "car" },
    { category = "sedans", categoryLabel = "Sedans", price = 80000, model = "washington", name = "Washington", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 500000, model = "windsor", name = "Windsor", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 600000, model = "windsor2", name = "Windsor Drop", type = "car" },
    { category = "motorcycles", categoryLabel = "Motos", price = 40000, model = "wolfsbane", name = "Woflsbane", type = "car" },
    { category = "muscle", categoryLabel = "Muscle", price = 100000, model = "yosemite", name = "Yosemite", type = "car" },
    { category = "vans", categoryLabel = "Vans", price = 90000, model = "youga", name = "Youga", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 250000, model = "z190", name = "Z190", type = "car" },
    { category = "super", categoryLabel = "Super", price = 2500000, model = "zentorno", name = "Zentorno", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 250000, model = "zion", name = "Zion", type = "car" },
    { category = "coupes", categoryLabel = "Coupés", price = 300000, model = "zion2", name = "Zion Cabrio", type = "car" },
    { category = "sportsclassics", categoryLabel = "Sports Classics", price = 700000, model = "ztype", name = "Z-Type", type = "car" },
}
