function ShowHelpNotification(msg)
    if msg then
        msg = msg:gsub("~h~(.-)~s~", "<b>%1</b>")
        msg = msg:gsub("%*%*(.-)%*%*", "<b>%1</b>")
        msg = msg:gsub("*", "")
        msg = msg:gsub("~r~", "<span style='color:rgb(224, 50, 50);'>")
        msg = msg:gsub("~b~", "<span style='color:rgb(93, 182, 229);'>")
        msg = msg:gsub("~g~", "<span style='color:rgb(114, 204, 114);'>")
        msg = msg:gsub("~y~", "<span style='color:rgb(240, 200, 80);'>")
        msg = msg:gsub("~d~", "<span style='color:rgb(47, 92, 115);'>")
        msg = msg:gsub("~p~", "<span style='color:rgb(132, 102, 226);'>")
        msg = msg:gsub("~c~", "<span style='color:rgb(155, 155, 155);'>")
        msg = msg:gsub("~m~", "<span style='color:rgb(77, 77, 77);'>")
        msg = msg:gsub("~u~", "<span style='color:rgb(0, 0, 0);'>")
        msg = msg:gsub("~w~", "<span style='color:rgb(255, 255, 255);'>")
        msg = msg:gsub("~o~", "<span style='color:rgb(255, 133, 85);'>")
        msg = msg:gsub("~q~", "<span style='color:rgb(203, 54, 148);'>")
        msg = msg:gsub("~s~", "</span>")
        msg = msg:gsub("~h~", "<b>")
        msg = msg:gsub("~n~", "<br>")
        msg = msg:gsub("\n", "<br>")
        msg = msg:gsub("~input~", "<span class = 'INPUT_CONTEXT'>")
        msg = msg:gsub("%[A%]", "<span class = 'INPUT_CONTEXT'>A</span>")
        msg = msg:gsub("%[B%]", "<span class = 'INPUT_CONTEXT'>B</span>")
        msg = msg:gsub("%[C%]", "<span class = 'INPUT_CONTEXT'>C</span>")
        msg = msg:gsub("%[D%]", "<span class = 'INPUT_CONTEXT'>D</span>")
        msg = msg:gsub("%[E%]", "<span class = 'INPUT_CONTEXT'>E</span>")
        msg = msg:gsub("%[F%]", "<span class = 'INPUT_CONTEXT'>F</span>")
        msg = msg:gsub("%[G%]", "<span class = 'INPUT_CONTEXT'>G</span>")
        msg = msg:gsub("%[H%]", "<span class = 'INPUT_CONTEXT'>H</span>")
        msg = msg:gsub("%[I%]", "<span class = 'INPUT_CONTEXT'>I</span>")
        msg = msg:gsub("%[J%]", "<span class = 'INPUT_CONTEXT'>J</span>")
        msg = msg:gsub("%[K%]", "<span class = 'INPUT_CONTEXT'>K</span>")
        msg = msg:gsub("%[L%]", "<span class = 'INPUT_CONTEXT'>L</span>")
        msg = msg:gsub("%[M%]", "<span class = 'INPUT_CONTEXT'>M</span>")
        msg = msg:gsub("%[N%]", "<span class = 'INPUT_CONTEXT'>N</span>")
        msg = msg:gsub("%[O%]", "<span class = 'INPUT_CONTEXT'>O</span>")
        msg = msg:gsub("%[P%]", "<span class = 'INPUT_CONTEXT'>P</span>")
        msg = msg:gsub("%[Q%]", "<span class = 'INPUT_CONTEXT'>Q</span>")
        msg = msg:gsub("%[R%]", "<span class = 'INPUT_CONTEXT'>R</span>")
        msg = msg:gsub("%[S%]", "<span class = 'INPUT_CONTEXT'>S</span>")
        msg = msg:gsub("%[T%]", "<span class = 'INPUT_CONTEXT'>T</span>")
        msg = msg:gsub("%[U%]", "<span class = 'INPUT_CONTEXT'>U</span>")
        msg = msg:gsub("%[V%]", "<span class = 'INPUT_CONTEXT'>V</span>")
        msg = msg:gsub("%[W%]", "<span class = 'INPUT_CONTEXT'>W</span>")
        msg = msg:gsub("%[X%]", "<span class = 'INPUT_CONTEXT'>X</span>")
        msg = msg:gsub("%[Y%]", "<span class = 'INPUT_CONTEXT'>Y</span>")
        msg = msg:gsub("%[Z%]", "<span class = 'INPUT_CONTEXT'>Z</span>")
        msg = msg:gsub("~INPUT_VEH_DUCK~", "<span class = 'INPUT_CONTEXT'>X</span>")
        msg = msg:gsub("~INPUT_CELLPHONE_LEFT~", "<span class = 'INPUT_CONTEXT'>←</span>")
        msg = msg:gsub("~INPUT_FRONTEND_LEFT~", "<span class = 'INPUT_CONTEXT'>←</span>")
        msg = msg:gsub("~INPUT_CELLPHONE_RIGHT~", "<span class = 'INPUT_CONTEXT'>→</span>")
        msg = msg:gsub("~INPUT_FRONTEND_RIGHT~", "<span class = 'INPUT_CONTEXT'>→</span>")
        msg = msg:gsub("~INPUT_FRONTEND_RDOWN~", "<span class = 'INPUT_CONTEXT'>↵</span>")
        msg = msg:gsub("~INPUT_FRONTEND_RRIGHT~", "<span class = 'INPUT_CONTEXT'>⌫</span>")
        msg = msg:gsub("~INPUT_MULTIPLAYER_INFO~", "<span class = 'INPUT_CONTEXT'>W</span>")
        msg = msg:gsub("~INPUT_CONTEXT~", "<span class = 'INPUT_CONTEXT'>E</span>")
        msg = msg:gsub("~INPUT_PICKUP~", "<span class = 'INPUT_CONTEXT'>E</span>")
        msg = msg:gsub("~INPUT_DETONATE~", "<span class = 'INPUT_CONTEXT'>G</span>")
        msg = msg:gsub("~INPUT_VEH_EXIT~", "<span class = 'INPUT_CONTEXT'>F</span>")
        msg = msg:gsub("~INPUT_RELOAD~", "<span class = 'INPUT_CONTEXT'>R</span>")
        msg = msg:gsub("~INPUT_THROW_GRENADE~", "<span class = 'INPUT_CONTEXT'>G</span>")
        msg = msg:gsub("~INPUT_VEH_FLY_ROLL_LEFT_ONLY~", "<span class = 'INPUT_CONTEXT'>4</span>")
        msg = msg:gsub("~INPUT_VEH_FLY_ROLL_RIGHT_ONLY~", "<span class = 'INPUT_CONTEXT'>6</span>")
        msg = msg:gsub("~INPUT_VEH_FLY_SELECT_TARGET_LEFT~", "<span class = 'INPUT_CONTEXT'>7</span>")
        msg = msg:gsub("~INPUT_VEH_FLY_SELECT_TARGET_RIGHT~", "<span class = 'INPUT_CONTEXT'>9</span>")
        msg = msg:gsub("~INPUT_FRONTEND_ACCEPT~", "<span class = 'INPUT_CONTEXT'>↵</span>")
        msg = msg:gsub("~INPUT_REPLAY_TIMELINE_PICKUP_CLIP~", "<span class = 'INPUT_CONTEXT'>X</span>")
        msg = msg:gsub("~INPUT_VEH_HEADLIGHT~", "<span class = 'INPUT_CONTEXT'>H</span>")
        msg = msg:gsub("~INPUT_CELLPHONE_OPTION~", "<span class = 'INPUT_CONTEXT'>Suppr</span>")
        msg = msg:gsub("~INPUT_MOVE_LEFT_ONLY~", "<span class = 'INPUT_CONTEXT'>Q</span>")
        msg = msg:gsub("~INPUT_MOVE_RIGHT_ONLY~", "<span class = 'INPUT_CONTEXT'>D</span>")

     --   ESX.ShowHelpNotification("Utilisez ~INPUT_MOVE_LEFT_ONLY~ et ~INPUT_MOVE_RIGHT_ONLY~ pour tourner la vue.")


        msg = msg:gsub("~INPUT_FRONTEND_PAUSE_ALTERNATE~", "<span class = 'INPUT_CONTEXT'>Echap</span>")
        msg = "<span style=color:currentColor>" .. msg .. "</span>"
    end

    SendNUIMessage({
        message = msg
    })
end

exports("ShowHelpNotification", ShowHelpNotification)

RegisterNetEvent('showHelpNotification')
AddEventHandler('showHelpNotification', function(msg)
    ShowHelpNotification(msg)
end)